# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.admission.stash.appscode.com
  labels:
    app: stash
spec:
  caBundle: ${SERVICE_SERVING_CERT_CA}
  group: admission.stash.appscode.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: stash-operator
    namespace: ${STASH_NAMESPACE}
  version: v1alpha1
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.admission.stash.appscode.com
  labels:
    app: stash
spec:
  caBundle: ${SERVICE_SERVING_CERT_CA}
  group: admission.stash.appscode.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: stash-operator
    namespace: ${STASH_NAMESPACE}
  version: v1beta1
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.repositories.stash.appscode.com
  labels:
    app: stash
spec:
  caBundle: ${SERVICE_SERVING_CERT_CA}
  group: repositories.stash.appscode.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: stash-operator
    namespace: ${STASH_NAMESPACE}
  version: v1alpha1
