apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: admission.stash.appscode.com
  labels:
    app: stash
webhooks:
- name: deployment.admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/deployments
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - apps
    - extensions
    apiVersions:
    - "*"
    resources:
    - deployments
  failurePolicy: Ignore
  ${STASH_WEBHOOK_SIDE_EFFECTS}
- name: daemonset.admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/daemonsets
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - apps
    - extensions
    apiVersions:
    - "*"
    resources:
    - daemonsets
  failurePolicy: Ignore
  ${STASH_WEBHOOK_SIDE_EFFECTS}
- name: statefulset.admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/statefulsets
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    apiGroups:
    - apps
    apiVersions:
    - "*"
    resources:
    - statefulsets
  failurePolicy: Ignore
  ${STASH_WEBHOOK_SIDE_EFFECTS}
- name: replicationcontroller.admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/replicationcontrollers
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - ""
    apiVersions:
    - "*"
    resources:
    - replicationcontrollers
  failurePolicy: Ignore
  ${STASH_WEBHOOK_SIDE_EFFECTS}
- name: replicaset.admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/replicasets
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - apps
    - extensions
    apiVersions:
    - "*"
    resources:
    - replicasets
  failurePolicy: Ignore
  ${STASH_WEBHOOK_SIDE_EFFECTS}
- name: deploymentconfig.admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/deploymentconfigs
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - apps.openshift.io
    apiVersions:
    - "*"
    resources:
    - deploymentconfigs
  failurePolicy: Ignore
  ${STASH_WEBHOOK_SIDE_EFFECTS}
