apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stash-operator
  namespace: $STASH_OPERATOR
  labels:
    app: stash
  initializers:
    pending: []
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash
  template:
    metadata:
      labels:
        app: stash
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: $STASH_SERVICE_ACCOUNT
      containers:
      - name: operator
        args:
        - run
        - --v=3
        - --rbac=$STASH_ENABLE_RBAC
        image: appscode/stash:0.6.3
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
      - name: pushgateway
        args:
        - -web.listen-address=:56789
        - -persistence.file=/var/pv/pushgateway.dat
        image: prom/pushgateway:v0.4.0
        ports:
        - containerPort: 56789
          name: pushgateway
          protocol: TCP
        volumeMounts:
          - mountPath: /var/pv
            name: data-volume
          - mountPath: /tmp
            name: stash-scratchdir
      volumes:
        - emptyDir: {}
          name: data-volume
        - emptyDir: {}
          name: stash-scratchdir
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: stash-operator
  namespace: $STASH_OPERATOR
  labels:
    app: stash
spec:
  ports:
  - name: pushgateway
    port: 56789
    targetPort: pushgateway
  - name: http
    port: 56790
    targetPort: http
  selector:
    app: stash
