apiVersion: apps/v1
kind: Deployment
metadata:
  name: stash-operator
  namespace: ${STASH_NAMESPACE}
  labels:
    app: stash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash
  template:
    metadata:
      labels:
        app: stash
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: ${STASH_SERVICE_ACCOUNT}
      imagePullSecrets: [${STASH_IMAGE_PULL_SECRET}]
      containers:
      - name: operator
        image: ${STASH_DOCKER_REGISTRY}/stash:${STASH_IMAGE_TAG}
        imagePullPolicy: ${STASH_IMAGE_PULL_POLICY}
        args:
        - run
        - --v=3
        - --rbac=${STASH_ENABLE_RBAC}
        - --docker-registry=${STASH_DOCKER_REGISTRY}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --service-name=${STASH_SERVICE_NAME}
        - --enable-validating-webhook=${STASH_ENABLE_VALIDATING_WEBHOOK}
        - --bypass-validating-webhook-xray=${STASH_BYPASS_VALIDATING_WEBHOOK_XRAY}
        - --enable-status-subresource=${STASH_ENABLE_STATUS_SUBRESOURCE}
        - --use-kubeapiserver-fqdn-for-aks=${STASH_USE_KUBEAPISERVER_FQDN_FOR_AKS}
        - --enable-analytics=${STASH_ENABLE_ANALYTICS}
        ports:
        - containerPort: 8443
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
      - name: pushgateway
        args:
        - --web.listen-address=:56789
        - --persistence.file=/var/pv/pushgateway.dat
        image: prom/pushgateway:v0.5.2
        ports:
        - containerPort: 56789
          name: pushgateway
          protocol: TCP
        volumeMounts:
        - mountPath: /var/pv
          name: data-volume
        - mountPath: /tmp
          name: stash-scratchdir
      volumes:
      - emptyDir: {}
        name: data-volume
      - emptyDir: {}
        name: stash-scratchdir
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: stash-apiserver-cert
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      priorityClassName: system-cluster-critical
---
# kube lacks the service serving cert signer, so provide a manual secret for it
apiVersion: v1
kind: Secret
metadata:
  name: stash-apiserver-cert
  namespace: ${STASH_NAMESPACE}
  labels:
    app: stash
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_SERVING_CERT}
  tls.key: ${TLS_SERVING_KEY}
---
# to be able to expose TSB inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: ${STASH_SERVICE_NAME}
  namespace: ${STASH_NAMESPACE}
  labels:
    app: stash
spec:
  ports:
  - name: api
    port: 443
    targetPort: 8443
  - name: pushgateway
    port: 56789
    targetPort: 56789
  selector:
    app: stash
