apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: stash-operator
  name: stash-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-operator
  template:
    metadata:
      labels:
        app: stash-operator
    spec:
      containers:
      - name: stash-operator
        args:
        - run
        - --v=3
        image: appscode/stash:0.1.0
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
      - name: pushgateway
        args:
        - -web.listen-address=:56789
        - -persistence.file=/var/pv/pushgateway.dat
        image: prom/pushgateway:v0.4.0
        ports:
        - containerPort: 56789
          name: pushgateway
          protocol: TCP
        volumeMounts:
          - mountPath: /var/pv
            name: data-volume
          - mountPath: /tmp
            name: stash-scratchdir
      volumes:
        - emptyDir: {}
          name: data-volume
        - emptyDir: {}
          name: stash-scratchdir
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stash-operator
  name: stash-operator
  namespace: kube-system
spec:
  ports:
  - name: pushgateway
    port: 56789
    targetPort: pushgateway
  - name: http
    port: 56790
    targetPort: http
  selector:
    app: stash-operator
