apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: stash
  name: stash-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - stash.appscode.com
  resources:
  - restics
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - replicasets
  - daemonsets
  verbs: ["list", "watch", "patch"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["list", "watch", "patch"]
- apiGroups: [""]
  resources:
  - namespaces
  - replicationcontrollers
  verbs: ["list", "watch", "patch"]
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", delete"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs: ["get", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: stash
  name: stash-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stash-operator
subjects:
- kind: ServiceAccount
  name: stash-operator
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: stash
  name: stash-operator
  namespace: kube-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: stash
  name: stash-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash
  template:
    metadata:
      labels:
        app: stash
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: stash-operator
      containers:
      - name: operator
        args:
        - run
        - --v=3
        - --rbac=true
        image: appscode/stash:0.5.0
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
      - name: pushgateway
        args:
        - -web.listen-address=:56789
        - -persistence.file=/var/pv/pushgateway.dat
        image: prom/pushgateway:v0.4.0
        ports:
        - containerPort: 56789
          name: pushgateway
          protocol: TCP
        volumeMounts:
          - mountPath: /var/pv
            name: data-volume
          - mountPath: /tmp
            name: stash-scratchdir
      volumes:
        - emptyDir: {}
          name: data-volume
        - emptyDir: {}
          name: stash-scratchdir
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stash
  name: stash-operator
  namespace: kube-system
spec:
  ports:
  - name: pushgateway
    port: 56789
    targetPort: pushgateway
  - name: http
    port: 56790
    targetPort: http
  selector:
    app: stash
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: stash
  name: stash-sidecar
rules:
- apiGroups:
  - stash.appscode.com
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["get"]
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - replicasets
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - replicationcontrollers
  - secrets
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create"]
