apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: deployment-demo
  name: workload
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-demo
      name: busybox
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
      restartPolicy: Always
      volumes:
      - gitRepo:
          repository: https://github.com/appscode/stash-data.git
        name: source-data
---
apiVersion: v1
data:
  RESTIC_PASSWORD: bm90QHNlY3JldA==
kind: Secret
metadata:
  name: deployment-secret
  namespace: default
type: Opaque
---
apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: deployment-restic
  namespace: default
spec:
  selector:
    matchLabels:
      app: deployment-demo
  fileGroups:
  - path: /source/data
    retentionPolicy:
      keepLast: 5
  backend:
    local:
      path: /repo
      volume:
        emptyDir: {}
        name: repo
    repositorySecretName: deployment-secret
  schedule: '@every 1m'
  volumeMounts:
  - mountPath: /source/data
    name: source-data
