apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: pg-backup
spec:
  steps:
  - name: pg-backup
    params:
    - name: outputDir
      value: /etc/backup # specified
    - name: scratchDirVolume
      value: scratch-volume # specified
    - name: secretVolume
      value: secret-volume # specified
    - name: outputVolume
      value: output-volume # specified
  - name: update-status
    params:
    - name: outputDir
      value: /etc/backup # specified
    - name: outputVolume
      value: output-volume # specified
  volumes:
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
  - name: scratch-volume
    emptyDir: {}
  - name: output-volume
    emptyDir: {}
