apiVersion: v1
kind: Service
metadata:
  name: {{ template "stash.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "stash.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: admission
    port: 443
    targetPort: 8443
  # Port used to expose Prometheus pushgateway
  - name: pushgateway
    port: 56789
    protocol: TCP
    targetPort: 56789
  selector:
    app: "{{ template "stash.name" . }}"
    release: "{{ .Release.Name }}"
